/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_speextest_Speex */

#ifndef _Included_com_example_speextest_Speex
#define _Included_com_example_speextest_Speex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_speextest_Speex
 * Method:    open
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_example_speextest_Speex_open
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_example_speextest_Speex
 * Method:    AEC
 * Signature: ([S[S[SZ)V
 */
JNIEXPORT void JNICALL Java_com_example_speextest_Speex_AEC
  (JNIEnv *, jclass, jshortArray, jshortArray, jshortArray);

/*
 * Class:     com_example_speextest_Speex
 * Method:    playback
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_com_example_speextest_Speex_playback
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     com_example_speextest_Speex
 * Method:    capture
 * Signature: ([S[S)V
 */
JNIEXPORT void JNICALL Java_com_example_speextest_Speex_capture
  (JNIEnv *, jclass, jshortArray, jshortArray);

/*
 * Class:     com_example_speextest_Speex
 * Method:    test
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_speextest_Speex_test
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
